FROM node:24-bookworm-slim AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_SIBAY_ADDRESS
ARG NEXT_PUBLIC_SIBAY_PHONE
ARG NEXT_PUBLIC_SIBAY_SCHEDULE
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SIBAY_ADDRESS=$NEXT_PUBLIC_SIBAY_ADDRESS
ENV NEXT_PUBLIC_SIBAY_PHONE=$NEXT_PUBLIC_SIBAY_PHONE
ENV NEXT_PUBLIC_SIBAY_SCHEDULE=$NEXT_PUBLIC_SIBAY_SCHEDULE
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:24-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1
COPY --from=build --chown=node:node /app /app
RUN mkdir -p /app/var/price-uploads && chown -R node:node /app/var
USER node
EXPOSE 3000
CMD ["npm", "start"]
