'use client';
import Image from 'next/image'; import Link from 'next/link';
import { ArrowRight, Check, RefreshCcw, ShieldCheck, Store } from 'lucide-react';
import { categories, featuredProducts } from '@/data/catalog'; import { CITY_LIST } from '@/config/cities';
import { useCity } from '@/components/providers/city-provider'; import { ProductCard } from './product-card';
export function HomePage() { const { cityId, setCityId } = useCity(); return <main>
  <section className="hero"><Image src="/images/hero-phone.png" alt="Флагманский смартфон в графитовом корпусе" fill priority sizes="100vw" className="hero-image" /><div className="container hero-content"><p className="eyebrow">НОВОЕ ПОКОЛЕНИЕ ТЕХНИКИ</p><h1>ПОРА<br />ОБНОВИТЬСЯ<span>.</span></h1><p className="hero-copy">Техника, которую хочется.<br />Цены, которые приятно видеть.</p><div className="hero-actions"><Link className="button button-dark" href="#каталог">Смотреть каталог <ArrowRight size={17} /></Link><Link className="button button-ghost" href="#trade-in">Trade-In</Link></div></div><div className="container hero-note"><span>iPhone 17 Pro</span><span>от 109 990 ₽</span></div></section>
  <section className="categories-section"><div className="container"><div className="section-kicker"><h2>Выберите своё</h2><Link href="#каталог">Весь каталог <ArrowRight size={15} /></Link></div><div className="category-scroll">{categories.map((category, index) => <Link href="#каталог" className="category-item" key={category}><span className={`category-visual visual-${index % 4}`}><Image src={index < 3 ? '/images/hero-phone.png' : '/images/tech-still-life.png'} alt="" fill sizes="130px" /></span><strong>{category}</strong></Link>)}</div></div></section>
  <section id="каталог" className="products-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">ВЫБОР APPGRADE</p><h2>Сейчас выбирают</h2></div><Link href="#каталог">Перейти в каталог <ArrowRight size={17} /></Link></div><div className="product-grid">{featuredProducts.map((product, index) => <ProductCard key={product.sku.id} product={product} index={index} />)}</div></div></section>
  <section className="container promo promo-dark"><div className="promo-copy"><p className="eyebrow">MACBOOK AIR</p><h2>Тонкий корпус.<br />Большие планы.</h2><p>Мощность, которая не требует лишних слов.</p><Link className="text-link" href="#каталог">Смотреть модели <ArrowRight size={18} /></Link></div><Image src="/images/tech-still-life.png" alt="Ноутбук и персональные устройства" fill sizes="(max-width: 768px) 100vw, 50vw" /></section>
  <section id="trade-in" className="trade-section"><div className="container trade-grid"><div><p className="eyebrow">TRADE-IN</p><h2>Старый iPhone может стоить больше, чем кажется.</h2><p>Оценим устройство за пару минут. Вы доплатите только разницу.</p><Link className="button button-light" href="#trade-in">Оценить устройство <ArrowRight size={17} /></Link></div><div className="trade-flow"><div><span>ВАШ СЕЙЧАС</span><strong>iPhone</strong></div><ArrowRight /><div className="trade-price"><span>ДО</span><strong>54 000 ₽</strong><small>в зачёт покупки</small></div><ArrowRight /><div><span>ВАШ СЛЕДУЮЩИЙ</span><strong>iPhone</strong></div></div></div></section>
  <section className="benefits container"><div className="section-heading"><div><p className="eyebrow">БЕЗ ЛИШНИХ СЛОВ</p><h2>Почему APPGRADE</h2></div></div><div className="benefit-list"><div><ShieldCheck /><h3>Оригинальная техника</h3><p>Только новые устройства с гарантией.</p></div><div><Check /><h3>Честная цена</h3><p>Помогаем выбрать, не навязывая лишнего.</p></div><div><RefreshCcw /><h3>Выгодный Trade-In</h3><p>Старое устройство работает на новую покупку.</p></div><div><Store /><h3>Три города</h3><p>Покупайте там, где вам удобно.</p></div></div></section>
  <section id="контакты" className="cities-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">МЫ РЯДОМ</p><h2>APPGRADE в трёх городах</h2></div><p>Адреса магазинов появятся после подтверждения.<br />Выберите город — цены и наличие будут актуальны для него.</p></div><div className="city-grid">{CITY_LIST.map((city, index) => <button key={city.id} onClick={() => setCityId(city.id)} className={cityId === city.id ? 'active' : ''}><span>0{index + 1}</span><strong>{city.name}</strong><small>{cityId === city.id ? 'Выбранный город' : 'Выбрать город'}</small><ArrowRight /></button>)}</div></div></section>
</main>; }
